package com.webforj.addons.services.webauthn.data;

import com.google.gson.annotations.SerializedName;

/**
 * Enumeration representing the preference of attestation conveyance during
 * credential generation in Web Authentication (WebAuthn). Relying Parties can
 * use these preferences to specify how they wish to receive attestation
 * statements from authenticators.
 *
 * @see <a href=
 *      "https://www.w3.org/TR/webauthn-3/#enum-attestation-convey">Attestation
 *      Conveyance Preference</a>
 *
 * @author @ElyasSalar
 * @since 1.00
 */
public enum AttestationConveyancePreference {
	/**
	 * Indicates that the Relying Party wants to receive the attestation statement
	 * directly as generated by the authenticator without any modifications.
	 */
	@SerializedName("direct")
	DIRECT,

	/**
	 * Indicates that the Relying Party wants to receive an attestation statement
	 * that may include uniquely identifying information. This preference is
	 * typically chosen for controlled deployments within enterprises where
	 * registrations need to be tied to specific authenticators. User agents must
	 * not provide such attestation unless explicitly permitted by the user agent or
	 * authenticator configuration for the requested RP ID. If permitted, the user
	 * agent should signal to the authenticator during invocation that enterprise
	 * attestation is requested.
	 */
	@SerializedName("enterprise")
	ENTERPRISE,

	/**
	 * Indicates that the Relying Party wants to receive a verifiable attestation
	 * statement, but allows the client to decide how to obtain it. The client may
	 * substitute an authenticator-generated attestation statement with one
	 * generated by an Anonymization CA to protect user privacy. However, there's no
	 * guarantee of obtaining a verifiable attestation statement in this case,
	 * especially if the authenticator uses self attestation.
	 */
	@SerializedName("indirect")
	INDIRECT,

	/**
	 * Indicates that the Relying Party is not interested in receiving authenticator
	 * attestation. The client may replace any authenticator-generated attestation
	 * statement with a None attestation statement. This preference is typically
	 * chosen to avoid obtaining user consent for relaying identifying information
	 * or to simplify the process.
	 */
	@SerializedName("none")
	NONE
}
